{
 "title": "ONTAP: MetroCluster",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(aggr_new_status{system_type!=\"7mode\",datacenter=\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(aggr_new_status{system_type!=\"7mode\",datacenter=\"$Datacenter\",cluster=\"$Cluster\"}, node)"
    }
   },
   {
    "name": "Aggr",
    "query": {
     "query": "label_values(aggr_new_status{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}, aggr)"
    }
   },
   { "name": "TopResources", "query": "1,2,3,4,5,6,8,10,15,20,40" }
  ]
 },
 "panels": [
  {
   "title": "Highlights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Volume Average Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(volume_avg_latency{datacenter=\"$Datacenter\", cluster=\"$Cluster\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "FCVI Write Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(fcvi_rdma_write_avg_latency{cluster=\"$Cluster\", datacenter=\"$Datacenter\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "FCVI Write Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(fcvi_rdma_write_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "FCVI Write IOPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(fcvi_rdma_write_ops{cluster=\"$Cluster\", datacenter=\"$Datacenter\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_avg_processor_busy{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Max Disk Utilization Per Aggregate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(aggr_disk_max_busy{cluster=\"$Cluster\", datacenter=\"$Datacenter\", node=~\"$Node\", aggr=~\"$Aggr\"})"
    }
   ]
  },
  {
   "title": "FCVI Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by(node) (fcvi_rdma_write_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "FCVI Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by (node) (fcvi_rdma_write_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "FCVI IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg by(node) (fcvi_rdma_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "MetroCluster FCVI Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "FCVI Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg (fcvi_rdma_write_avg_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "FCVI Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg(fcvi_rdma_write_throughput{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "FCVI Write IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg(fcvi_rdma_write_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Write"
      }
     ]
    }
   ]
  },
  {
   "title": "MetroCluster Disk Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk Utilization per Plex",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk($TopResources,aggr_disk_busy{cluster=\"$Cluster\", datacenter=\"$Datacenter\", node=~\"$Node\" , aggr=~\"$Aggr\"})",
       "legendFormat": "{{node}}.{{aggr}}.{{plex}}"
      }
     ]
    },
    {
     "title": "Disk Utilization per Plex Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk($TopResources,avg(label_join(aggr_disk_busy{datacenter=\"$Datacenter\", cluster=\"$Cluster\", node=~\"$Node\", aggr=~\"$Aggr\"},\"Field\", \".\", \"cluster\", \"aggr\", \"plex\")) by (Field))"
      }
     ]
    },
    {
     "title": "User Reads per Disk per Plex",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk($TopResources,aggr_disk_user_reads{cluster=\"$Cluster\", datacenter=\"$Datacenter\", node=~\"$Node\" , aggr=~\"$Aggr\"})",
       "legendFormat": "{{node}}.{{aggr}}.{{plex}}"
      }
     ]
    },
    {
     "title": "User Writes per Disk per Plex",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk($TopResources,aggr_disk_user_writes{cluster=\"$Cluster\", datacenter=\"$Datacenter\", node=~\"$Node\" , aggr=~\"$Aggr\"})",
       "legendFormat": "{{node}}.{{aggr}}.{{plex}}"
      }
     ]
    },
    {
     "title": "User Read Latency per 4KB IO per Plex",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk($TopResources,aggr_disk_user_read_latency{cluster=\"$Cluster\", datacenter=\"$Datacenter\", node=~\"$Node\" , aggr=~\"$Aggr\"})",
       "legendFormat": "{{node}}.{{aggr}}.{{plex}}"
      }
     ]
    },
    {
     "title": "User Write Latency per 4KB IO per Plex",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk($TopResources,aggr_disk_user_write_latency{cluster=\"$Cluster\", datacenter=\"$Datacenter\", node=~\"$Node\" , aggr=~\"$Aggr\"})",
       "legendFormat": "{{node}}.{{aggr}}.{{plex}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk and Tape Adapter Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Adapter Read Data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources,hostadapter_bytes_read{cluster=\"$Cluster\", datacenter=\"$Datacenter\", node=~\"$Node\"}) by (node)",
       "legendFormat": "{{node}} - {{hostadapter}}"
      }
     ]
    },
    {
     "title": "Adapter Write Data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources,hostadapter_bytes_written{cluster=\"$Cluster\", datacenter=\"$Datacenter\", node=~\"$Node\"}) by (node)",
       "legendFormat": "{{node}} - {{hostadapter}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MetroCluster FibreBridge/Array Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Read Latency from FibreBridge/Array WWPN",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "path_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Read Data from FibreBridge/Array WWPN",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "path_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Read IOPs from FibreBridge/Array WWPN",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "path_read_iops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write Latency to FibreBridge/Array WWPN",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "path_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write Data to FibreBridge/Array WWPN",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "path_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write IOPs to FibreBridge/Array WWPN",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "path_write_iops{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}