{
 "title": "ONTAP: Headroom",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\"}, cluster)"
    }
   },
   { "name": "Interval", "query": "hourly, daily, weekly, monthly" }
  ]
 },
 "panels": [
  {
   "title": "Aggregate Headroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "headroom_aggr_current_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Current Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "headroom_aggr_current_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Current Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "headroom_aggr_current_utilization{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Optimal-Point Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "headroom_aggr_optimal_point_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Optimal-Point Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "headroom_aggr_optimal_point_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Optimal-Point Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "headroom_aggr_optimal_point_utilization{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "EWMA $Interval Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "headroom_aggr_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"latency\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "EWMA $Interval Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "headroom_aggr_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"ops\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "EWMA $Interval utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "headroom_aggr_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"utilization\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "EWMA $Interval Optimal-Point Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "headroom_aggr_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"optimal_point_latency\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "EWMA $Interval Optimal-Point Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "headroom_aggr_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"optimal_point_ops\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "EWMA $Interval Optimal-Point Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "headroom_aggr_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"optimal_point_utilization\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "CPU Headroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_current_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Current Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_current_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Current Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_current_utilization{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Optimal-Point Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_optimal_point_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Optimal-Point Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_cpu_optimal_point_ops{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Optimal-Point Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_cpu_optimal_point_utilization{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"latency\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"ops\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"utilization\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"optimal_point_latency\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"optimal_point_ops\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval}{datacenter=\"$Datacenter\",cluster=\"$Cluster\",metric=\"optimal_point_utilization\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}