{
 "title": "ONTAP: Shelf",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(shelf_labels{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(shelf_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "Shelf",
    "query": {
     "query": "label_values(shelf_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}, shelf)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  {
   "title": "Highlights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shelves",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(shelf_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}) by (shelf))"
    }
   ]
  },
  {
   "title": "Total Power (Shelf)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(shelf_power{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Max Shelf temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(shelf_max_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Temperature Avg",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelf_temperature_reading{datacenter=\"$Datacenter\",cluster=\"$Cluster\",shelf=~\"$Shelf\"})"
    }
   ]
  },
  {
   "title": "Fan RPM Avg",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelf_fan_rpm{datacenter=\"$Datacenter\",cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Max Shelf Fan Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(shelf_max_fan_speed{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Custom Sensor Avg",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelf_sensor_reading{datacenter=\"$Datacenter\",cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Power used 24h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(shelf_psu_power_drawn{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}[24h]))"
    }
   ]
  },
  {
   "title": "Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Storage Shelves",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "shelf_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "shelf_disk_count{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "shelf_new_status{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "shelf_power{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "shelf_average_ambient_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "shelf_min_ambient_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "shelf_max_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "shelf_average_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "shelf_min_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "shelf_max_fan_speed{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "shelf_average_fan_speed{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "shelf_min_fan_speed{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Total Shelves by Power Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "topk($TopResources,shelf_power{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})",
     "legendFormat": "{{shelf}} ({{cluster}})"
    }
   ]
  },
  {
   "title": "Top Shelves by Average Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "topk($TopResources,shelf_average_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})",
     "legendFormat": "{{shelf}} ({{cluster}})"
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 23 },
   "repeat": "TempShelf",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shelf_temperature_reading{datacenter=\"$Datacenter\",cluster=\"$Cluster\",shelf=~\"$Shelf\"}",
     "legendFormat": "{{shelf}} · {{sensor_id}}"
    }
   ]
  },
  {
   "title": "Cooling Sensors",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "repeat": "FanShelf",
   "fieldConfig": { "defaults": { "unit": "RPM" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shelf_fan_rpm{datacenter=\"$Datacenter\",cluster=\"$Cluster\",shelf=~\"$Shelf\"}",
     "legendFormat": "{{shelf}} · {{fan_id}}"
    }
   ]
  },
  {
   "title": "Voltage & PSU Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Voltage Sensors",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "shelf_voltage_reading{datacenter=\"$Datacenter\",cluster=\"$Cluster\",shelf=~\"$Shelf\"}",
     "legendFormat": "{{shelf}} · {{sensor_id}}"
    }
   ]
  },
  {
   "title": "Energy Drawn from PSUs",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 4, "x": 7, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(shelf_psu_power_drawn{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}) by (shelf, psu_id)",
     "legendFormat": "{{shelf}} - PSU {{psu_id}}"
    }
   ]
  },
  {
   "title": "Power Rating from PSUs",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 4, "x": 11, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(shelf_psu_power_rating{datacenter=\"$Datacenter\",cluster=\"$Cluster\"}) by (shelf, psu_id)",
     "legendFormat": "{{shelf}} - PSU {{psu_id}}"
    }
   ]
  },
  {
   "title": "Custom Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Custom Sensors - Shelf",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 58 },
   "repeat": "SensShelf",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shelf_sensor_reading{datacenter=\"$Datacenter\",cluster=\"$Cluster\",shelf=~\"$Shelf\"}",
     "legendFormat": "{{shelf}} · {{sensor_id}}"
    }
   ]
  }
 ]
}