{
 "title": "ONTAP: Network with NVMe/FC",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(nic_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(nic_labels{system_type!=\"7mode\",cluster=\"$Cluster\"}, node)"
    }
   },
   {
    "name": "Eth",
    "query": {
     "query": "label_values(nic_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}, nic)"
    }
   },
   {
    "name": "FCP",
    "query": {
     "query": "label_values(fcp_total_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}, port)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,20,50,100,250,500,1000"
   }
  ]
 },
 "panels": [
  {
   "title": "Ethernet Send",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nic_tx_bytes{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nic=~\"$Eth\"})"
    }
   ]
  },
  {
   "title": "Ethernet Receive",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nic_rx_bytes{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nic=~\"$Eth\"})"
    }
   ]
  },
  {
   "title": "FCP Receive",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fcp_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})"
    }
   ]
  },
  {
   "title": "FCP Send",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fcp_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})"
    },
    {}
   ]
  },
  {
   "title": "NVMe/FC Receive",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fcp_nvmf_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})"
    }
   ]
  },
  {
   "title": "NVMe/FC Send",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fcp_nvmf_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})"
    },
    {}
   ]
  },
  {
   "title": "Ethernet Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ethernet ports",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "nic_labels{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
      },
      {
       "expr": "nic_new_status{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
      },
      {
       "expr": "nic_util_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
      },
      {
       "expr": "nic_tx_bytes{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
      },
      {
       "expr": "nic_rx_bytes{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
      }
     ]
    },
    {
     "title": "Send Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources, nic_tx_bytes{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{nic}}"
      }
     ]
    },
    {
     "title": "Receive Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources, nic_rx_bytes{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{nic}}"
      }
     ]
    },
    {
     "title": "Port Utilization %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "nic_util_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}",
       "legendFormat": "{{node}} {{nic}}"
      }
     ]
    },
    {
     "title": "Send Errors",
     "type": "timeseries",
     "description": "Summarized on Cluster or Node level. Select Eth to show for a specific Ethernet Port.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (cluster) (nic_tx_total_errors{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nic=~\"$Eth\"})",
       "legendFormat": "TOTAL"
      },
      {
       "expr": "sum by (cluster) (nic_tx_hw_errors{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nic=~\"$Eth\"})",
       "legendFormat": "HW"
      }
     ]
    },
    {
     "title": "Receive Errors",
     "type": "timeseries",
     "description": "Summarized on Cluster or Node level. Select Eth to show for a specific Ethernet Port.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (cluster) (nic_rx_total_errors{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nic=~\"$Eth\"})",
       "legendFormat": "TOTAL"
      },
      {
       "expr": "sum by (cluster) (nic_rx_alignment_errors{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nic=~\"$Eth\"})",
       "legendFormat": "ALIGNMENT"
      },
      {
       "expr": "sum by (cluster) (nic_rx_crc_errors{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nic=~\"$Eth\"})",
       "legendFormat": "CRC"
      },
      {
       "expr": "sum by (cluster) (nic_rx_length_errors{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",nic=~\"$Eth\"})",
       "legendFormat": "LENGTH"
      }
     ]
    }
   ]
  },
  {
   "title": "FibreChannel Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "FCP ports",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "fcp_util_percent{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
      },
      {
       "expr": "fcp_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
      },
      {
       "expr": "fcp_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
      }
     ]
    },
    {
     "title": "Send Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources, fcp_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    },
    {
     "title": "Receive Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk($TopResources, fcp_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    },
    {
     "title": "Send Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk($TopResources, fcp_avg_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    },
    {
     "title": "Receive Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk($TopResources, fcp_avg_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    },
    {
     "title": "Transmission interrupts",
     "type": "timeseries",
     "description": "Summarized on Cluster or Node level. Select FCP to show for a specific FibreChannel Port.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(fcp_int_count{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "interrupts"
      },
      {
       "expr": "sum(fcp_invalid_transmission_word{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "invalid transmission words (blocks)"
      },
      {
       "expr": "sum(fcp_isr_count{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "interrupt responses"
      },
      {
       "expr": "sum(fcp_spurious_int_count{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "spurious interrupts"
      },
      {
       "expr": "sum(fcp_invalid_crc{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "invalid CRCs"
      }
     ]
    },
    {
     "title": "Transmission errors",
     "type": "timeseries",
     "description": "Summarized on Cluster or Node level. Select FCP to show for a specific FibreChannel Port.",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(fcp_discarded_frames_count{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "discarded frames"
      },
      {
       "expr": "sum(fcp_loss_of_signal{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "loss of signal"
      },
      {
       "expr": "sum(fcp_loss_of_sync{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "loss of sync"
      },
      {
       "expr": "sum(fcp_prim_seq_err{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "primitive sequence errors"
      },
      {
       "expr": "sum(fcp_queue_full{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "queue full"
      },
      {
       "expr": "sum(fcp_threshold_full{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\",port=~\"$FCP\"})",
       "legendFormat": "threshold full"
      }
     ]
    },
    {
     "title": "Link Down",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($TopResources, fcp_link_down{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    },
    {
     "title": "Link Failure",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($TopResources, fcp_link_failure{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "{{node}} - {{port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NVMe/FC Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NVMe/FC ports",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "fcp_nvmf_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
    },
    {
     "expr": "fcp_nvmf_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Send Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($TopResources, fcp_read_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
     "legendFormat": "{{node}} - {{port}}"
    }
   ]
  },
  {
   "title": "Receive Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($TopResources, fcp_write_data{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
     "legendFormat": "{{node}} - {{port}}"
    }
   ]
  },
  {
   "title": "Send Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk($TopResources, fcp_avg_read_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
     "legendFormat": "{{node}} - {{port}}"
    }
   ]
  },
  {
   "title": "Receive Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk($TopResources, fcp_avg_write_latency{datacenter=\"$Datacenter\",cluster=\"$Cluster\",node=~\"$Node\"})",
     "legendFormat": "{{node}} - {{port}}"
    }
   ]
  }
 ]
}