{
 "title": "Servicedesk - Platform",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1 style=\"font-size:5vw\">EBROKER</h1></center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"EB01 - Processing\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"EB02 - Processing\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"EB04 - Processing\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"EB05 - Processing\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"EB07 - Processing\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Eserver - Processing\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Transaction Log - Document status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(sum_over_time(app_monitoring_files_total[15m])) by (status) / on() group_left() sum(sum_over_time(app_monitoring_files_total[15m])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(app_monitoring_tlog{name=~\"OIOD.*\"}[$__range])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum_over_time(app_monitoring_tlog{name=~\"OIOH.*\"}[$__range])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Out OIOSI Default Queued",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=~\"oiosigw_default.app.queue\",job=\"rabbitmq\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Out OIOSI High Queued",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=~\"oiosigw_high.app.queue\",job=\"rabbitmq\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (windows_service_state{job=\"prod\", name=~\"guru.b2bi.ebroker.*\", state=\"running\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"KMD-OutgoingCRITICALFile1h\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Processing Engine - ebroker records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Processing Engine - ebroker records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"SOR Validation\"}",
     "legendFormat": "SOR Validation"
    }
   ]
  },
  {
   "title": "TechOps On-Call",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_monitoring_pagerduty", "legendFormat": "{{name}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"KMD-OutgoingNonCritcalFile2h\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Incoming GW - VLTrader records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Incoming GW - VLTrader records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Outgoing GW - VLTrader records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Outgoing GW - VLTrader records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Incoming GW - X400 records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Incoming GW - X400 records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Outgoing GW - X400 records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Outgoing GW - X400 records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Incoming GW - OIOSI records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Incoming GW - OIOSI records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Outgoing GW - OIOSI records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Outgoing GW - OIOSI records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "Transaction Log - Document Error Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum_over_time(app_monitoring_file_errors_total[15m])",
     "legendFormat": "{{errorCode}}"
    }
   ]
  },
  {
   "title": "High Outgoing OIOSI Delivered",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "sum_over_time(app_monitoring_tlog{name=~\"OIOH.*\"}[$__interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Default Outgoing OIOSI Delivered",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum_over_time(app_monitoring_tlog{name=~\"OIOD.*\"}[$__interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 } }
 ]
}