{
 "title": "TechOps - ES Cluster",
 "description": "Grafana Dashboards for Elasticsearch using Prometheus Datasource. Dashboard for Cluster Stats.",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(elasticsearch_indices_docs,cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
    }
   },
   {
    "name": "name",
    "label": "Node name",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},name)"
    }
   },
   {
    "name": "interval",
    "label": "Rate Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Level Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"red\"}==1 or (elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"yellow\"}==1)+2 or\n(elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"green\"}==1)+4 "
    }
   ]
  },
  {
   "title": "CPU  Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (elasticsearch_process_cpu_percent{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "JVM Max Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_jvm_memory_pool_max_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_pending_tasks{instance=\"$instance\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "stat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "stat",
   "description": "% Memory used by selected nodes, both heap and non-heap",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\"}) / sum (elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\"}) * 100"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Shards",
   "type": "stat",
   "description": "All shards, both primary and replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Primary Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "repeat": "shard_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "description": "Number of shards which are relocating to another node",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Delayed Shards",
   "type": "stat",
   "description": "Number of shards which are delayed relocating to another node",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\"} "
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "description": "Number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{cluster=\"$cluster\"} "
    }
   ]
  },
  { "title": "Nodes & Indices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Nodes Status",
   "type": "table",
   "description": "Current status of all nodes in cluster\n\n###### Notes\n\n+ `Blue`: constant value\n+ `Fds`: File Descriptors\n+ `Throttle`: flag `is_throttled`\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (name) (elasticsearch_os_cpu_percent{cluster=\"$cluster\"})",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum by (name) (elasticsearch_os_load5{cluster=\"$cluster\"})",
     "legendFormat": "Load Average"
    },
    {
     "expr": "sum by (name) (elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\"}) / sum by (name) (elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\"}) * 100",
     "legendFormat": "JVM Memory"
    },
    {
     "expr": "sum by (name) (elasticsearch_filesystem_data_available_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Disk Free Space"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{cluster=\"$cluster\",role=\"master\"})",
     "legendFormat": "Master Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{cluster=\"$cluster\",role=\"data\"})",
     "legendFormat": "Data Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{cluster=\"$cluster\",role=\"ingest\"})",
     "legendFormat": "Ingest Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{cluster=\"$cluster\",role=\"client\"})",
     "legendFormat": "Client Node"
    },
    {
     "expr": "1 - sum by (name) (elasticsearch_filesystem_data_available_bytes{cluster=\"$cluster\"}) / sum by (name) (elasticsearch_filesystem_data_size_bytes{cluster=\"$cluster\"})",
     "legendFormat": "% Disk Used"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_store_size_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Index Store Data"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_segments_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Segment Memory"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_segments_count{cluster=\"$cluster\"})",
     "legendFormat": "Segment Count"
    },
    {
     "expr": "sum by (name) (elasticsearch_process_open_files_count{cluster=\"$cluster\"})",
     "legendFormat": "Open Fds"
    },
    {
     "expr": "sum by (name) (elasticsearch_process_max_files_descriptors{cluster=\"$cluster\"})",
     "legendFormat": "Max Fds"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_indexing_is_throttled{cluster=\"$cluster\"})",
     "legendFormat": "Throttle"
    }
   ]
  },
  {
   "title": "Cluster Indexing - $cluster",
   "type": "graph",
   "description": "Indexing rate on cluster\n\n`ProcRate`: processing ability, which is the number of requests that Elasticsearch can handle. Estimation is based on the processed requests and processed time for these requests.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps", "label": "ReqRate" }
   ],
   "targets": [
    {
     "expr": "sum (rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "ReqRate"
    },
    {
     "expr": "1 / (\nsum (rate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\"}[$interval])) / \nsum (rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\"}[$interval]))\n)",
     "legendFormat": "ProcRate"
    }
   ]
  },
  {
   "title": "Cluster Search - $cluster",
   "type": "graph",
   "description": "Searching rate on cluster\n\n`ProcRate`: processing ability, which is the number of requests that Elasticsearch can handle. Estimation is based on the processed requests and processed time for those requests.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "reqps", "label": "ReqRate" }
   ],
   "targets": [
    {
     "expr": "sum (rate(elasticsearch_indices_search_query_total{cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "ReqRate"
    },
    {
     "expr": "1 / (\n(sum(rate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_fetch_time_seconds{cluster=\"$cluster\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_scroll_time_seconds{cluster=\"$cluster\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_suggest_time_seconds{cluster=\"$cluster\"}[$interval]))\n) /\nsum(rate(elasticsearch_indices_search_query_total{cluster=\"$cluster\"}[$interval]))\n)",
     "legendFormat": "ProcRate"
    }
   ]
  },
  {
   "title": "Indexing ReqRate (req/s)",
   "type": "graph",
   "description": "Indexing rate on data nodes",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",name=~\"$name\",es_data_node=\"true\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Search Query ReqRate (req/s)",
   "type": "graph",
   "description": "Search query rate on data nodes",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_total{cluster=\"$cluster\",name=~\"$name\",es_data_node=\"true\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Times Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Search Query Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval]) ",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Indexing Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Merging Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Refresh Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_refresh_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_refresh_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Throttle Time for Index Store",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_store_throttle_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_store_throttle_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  { "title": "Documents by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Documents Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(elasticsearch_indices_docs{cluster=\"$cluster\",name=~\"$name\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Merged Documents / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "locale", "label": "docs/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_docs_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_merges_docs_total{cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Deleted Documents",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs_deleted{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(elasticsearch_indices_docs_deleted{cluster=\"$cluster\",name=~\"$name\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Documents Index Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "index calls/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Merged Bytes / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_total_size_bytes_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents Deleted Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "locale", "label": "docs/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_docs_deleted{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_docs_deleted{cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Thread Pool by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Pool operations queued",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_thread_pool_queue_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread Pool operations completed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 62 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_thread_pool_completed_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread Pool operations rejected",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 62 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_thread_pool_rejected_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread Pool threads active",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_thread_pool_active_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread Pool current threads count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 68 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_thread_pool_threads_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread Pool largest threads count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 68 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_thread_pool_largest_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "JVM Memory Usage - $name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 71 },
   "repeat": "name",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",name=~\"$name\",area=\"heap\"}",
     "legendFormat": "Max heap"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",name=~\"$name\",area=\"heap\"}",
     "legendFormat": "Used heap"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",name=~\"$name\",area=\"non-heap\"}",
     "legendFormat": "Non-Heap"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",name=~\"$name\",area=\"heap\"} / elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",name=~\"$name\",area=\"heap\"} * 100",
     "legendFormat": "% Used Heap"
    }
   ]
  },
  { "title": "Disk and Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-\n(elasticsearch_filesystem_data_available_bytes{cluster=\"$cluster\",name=~\"$name\"} /\nelasticsearch_filesystem_data_size_bytes{cluster=\"$cluster\",name=~\"$name\"})\n)*100",
     "legendFormat": "{{name}}: {{path}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/sec" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_tx{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: sent"
    },
    {
     "expr": "irate(elasticsearch_transport_rx_size_bytes_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: received"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_open_files_count{cluster=\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Segments on Nodes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_count{cluster=\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "JVM Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "JVM GC Runs / s ",
   "type": "graph",
   "description": "Number of JVM GC runs in second by nodes.\nThreshold is 1 GC/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "JVM GC Runtime / s ",
   "type": "graph",
   "description": "JVM GC runtime in second by nodes\nThreshold is 40ms / s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=\"$cluster\",name=~\"$name\"}[5m]) * 1000",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  { "title": "File Descriptors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "File Descriptors - $name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 122 },
   "repeat": "name",
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_open_files_count{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Open Fds"
    },
    {
     "expr": "elasticsearch_process_max_files_descriptors{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Max Fds"
    },
    {
     "expr": "elasticsearch_process_open_files_count{cluster=\"$cluster\",name=~\"$name\"} / elasticsearch_process_max_files_descriptors{cluster=\"$cluster\",name=~\"$name\"} * 100",
     "legendFormat": "% Open Fds"
    }
   ]
  },
  {
   "title": "Transaction Log by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 },
   "collapsed": true,
   "panels": [
    {
     "title": "Translog operations / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "locale", "label": "op/s" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_translog_operations{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Translog Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 95 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_translog_operations{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Translog Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 95 },
     "yaxes": [
      { "format": "bytes", "label": "bytes/s" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_translog_size_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "OS CPU Usage",
   "type": "graph",
   "description": "% CPU used by OS",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "percent", "label": "% CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_os_cpu_percent{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "description": "% CPU used by process",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 138 },
   "yaxes": [
    { "format": "percent", "label": "% CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Index Memory - $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 }, "repeat": "name" },
  {
   "title": "Index Memory - Lucene - $name",
   "type": "graph",
   "description": "+ *Lucene Total*: Total heap memory used by Lucene for current index. This is the sum of other fields for primary and replica shards on this node.\n\n+ *Stored Fields*: Heap memory used by Stored Fields (e.g., _source). This is a part of Lucene Total.. \n\n+ *Doc Values*: Heap memory used by Doc Values. This is a part of Lucene Total.. \n\n+ *Norms*: Heap memory used by Norms (normalization factors for query-time, text scoring). This is a part of Lucene Total.\n\n+ *Terms*: (e.g., text). This is a part of Lucene Total.\n\n+ *Points*: Heap memory used by Points (e.g., numbers, IPs, and geo data). This is a part of Lucene Total.\n\n+ *Fixed Bitsets*: (e.g., text). This is a part of Lucene Total.\n\n+ *Term Vectors*: Heap memory used by Term Vectors. This is a part of Lucene Total.\n\n+ *Version Map*: Heap memory used by Versioning (e.g., updates and deletes). This is NOT a part of Lucene Total.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_stored_fields_memory_in_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Stored Fields"
    },
    {
     "expr": "elasticsearch_indices_segments_doc_values_memory_in_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Doc Values"
    },
    {
     "expr": "elasticsearch_indices_segments_norms_memory_in_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Norms"
    },
    {
     "expr": "elasticsearch_indices_segments_fixed_bit_set_memory_in_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Fixed Bitsets"
    },
    {
     "expr": "elasticsearch_indices_segments_term_vectors_memory_in_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Term Vectors"
    },
    {
     "expr": "elasticsearch_indices_segments_version_map_memory_in_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Version Map"
    },
    {
     "expr": "elasticsearch_indices_segments_terms_memory_in_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Terms"
    },
    {
     "expr": "elasticsearch_indices_segments_points_memory_in_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Points"
    },
    {
     "expr": "elasticsearch_indices_segments_memory_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Lucene Total"
    }
   ]
  },
  {
   "title": "Index Memory - Elasticsearch - $name",
   "type": "graph",
   "description": "+ *Query Cache*: Heap memory used by Query Cache (e.g., cached filters). This is for the same shards, but not a part of Lucene Total.. \n\n+ *Request Cache*: Heap memory used by Request Cache (e.g., instant aggregations). This is for the same shards, but not a part of Lucene Total.. \n\n+ *Fielddata*: Heap memory used by Fielddata (e.g., global ordinals or explicitly enabled fielddata on text fields). This is for the same shards, but not a part of Lucene Total.. \n\n+ *Index Writer*: Heap memory used by the Index Writer. This is NOT a part of Lucene Total.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_query_cache_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Query Cache"
    },
    {
     "expr": "elasticsearch_indices_request_cache_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Request Cache"
    },
    {
     "expr": "elasticsearch_indices_fielddata_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Fielddata"
    },
    {
     "expr": "elasticsearch_indices_segments_index_writer_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "Index Writer"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 229 } },
  {
   "title": "Shards Changes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 230 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{cluster=\"$cluster\"}",
     "legendFormat": "relocating"
    },
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=\"$cluster\"}",
     "legendFormat": "active primary"
    },
    {
     "expr": "elasticsearch_cluster_health_active_shards{cluster=\"$cluster\"}",
     "legendFormat": "active"
    },
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\"}",
     "legendFormat": "initializing"
    },
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{cluster=\"$cluster\"}",
     "legendFormat": "unassigned"
    },
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\"}",
     "legendFormat": "unassigned"
    }
   ]
  },
  {
   "title": "Segments Changes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 230 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (elasticsearch_indices_segment_count_total{cluster=~\"$cluster\"})",
     "legendFormat": "segments"
    }
   ]
  },
  {
   "title": "Total Scrapes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 230 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_total_scrapes{instance=\"$instance\"}",
     "legendFormat": "Scrapes"
    }
   ]
  }
 ]
}