{
 "title": "TechOps - VMware ESXi",
 "description": "VMware ESXi single instance graphs.",
 "tags": [
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "esxhost",
    "label": "esxhost",
    "query": {
     "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_product_info{host_name=~\"$esxhost\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Build",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_product_info{host_name=~\"$esxhost\"})",
     "legendFormat": "{{ build }}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_hardware_info{host_name=~\"$esxhost\"}) ",
     "legendFormat": "{{ hardware_model }}"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_product_info{host_name=~\"$esxhost\"})",
     "legendFormat": "{{ cluster_name }}"
    }
   ]
  },
  {
   "title": "Cpu Model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_hardware_info{host_name=~\"$esxhost\"}) ",
     "legendFormat": "{{ hardware_cpu_model }}"
    }
   ]
  },
  {
   "title": "ESXi host uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-vmware_host_boot_timestamp_seconds{host_name=~\"$esxhost\"} "
    }
   ]
  },
  {
   "title": "Cpu Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_num_cpu{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Memory Capaciy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_memory_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Host CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_host_cpu_usagemhz_average{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Current Cpu Ready",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_cpu_ready_summation{host_name=~\"$esxhost\"}/200",
     "legendFormat": "Cpu Ready"
    }
   ]
  },
  {
   "title": "Current Cpu Co-Stop",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_cpu_costop_summation{host_name=~\"$esxhost\"}/200"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_memory_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Host CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(vmware_host_cpu_usagemhz_average{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"})",
     "legendFormat": "Cpu Usage"
    },
    {
     "expr": "(vmware_host_cpu_demand_average{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"})",
     "legendFormat": "CPU Demand"
    }
   ]
  },
  {
   "title": "Host Cpu Contention",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vmware_host_cpu_ready_summation{host_name=~\"$esxhost\"}/200",
     "legendFormat": "Cpu Ready"
    },
    {
     "expr": "vmware_host_cpu_costop_summation{host_name=~\"$esxhost\"}/200",
     "legendFormat": "Cpu Co-Stop"
    },
    {
     "expr": "vmware_host_cpu_swapwait_summation{host_name=~\"$esxhost\"}/200",
     "legendFormat": "Cpu Swap Wait"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(vmware_host_mem_usage_average{host_name=~\"$esxhost\"}) * 100 / (vmware_host_memory_max{host_name=~\"$esxhost\"})",
     "legendFormat": "Memory Consumed"
    },
    {
     "expr": "(vmware_host_mem_active_average{host_name=~\"$esxhost\"})/1024 * 100 / (vmware_host_memory_max{host_name=~\"$esxhost\"})",
     "legendFormat": "Memory Active"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vmware_host_mem_vmmemctl_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Memory Balloon"
    },
    {
     "expr": "vmware_host_mem_latency_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Memory Latency"
    },
    {
     "expr": "vmware_host_mem_swapinRate_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Memory SwapInRate"
    },
    {
     "expr": "vmware_host_mem_swapoutRate_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Memory SwapOutRate"
    }
   ]
  },
  {
   "title": "Host Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "vmware_host_net_usage_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Total Usage"
    },
    {
     "expr": "vmware_host_net_bytesRX_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Usage RX"
    },
    {
     "expr": "vmware_host_net_bytesTX_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Usage TX"
    },
    {
     "expr": "sum(vmware_vm_net_broadcastRx_summation{host_name=~\"$esxhost\"})",
     "legendFormat": "Broadcast RX"
    },
    {
     "expr": "sum(vmware_vm_net_broadcastTx_summation{host_name=~\"$esxhost\"})",
     "legendFormat": "Broadcast TX"
    },
    {
     "expr": "sum(vmware_vm_net_multicastRx_summation{host_name=~\"$esxhost\"})",
     "legendFormat": "Multicast RX"
    },
    {
     "expr": "sum(vmware_vm_net_multicastTx_summation{host_name=~\"$esxhost\"})",
     "legendFormat": "Multicast TX"
    }
   ]
  },
  {
   "title": "Host Network Contention",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vmware_host_net_errorRX_summation{host_name=~\"$esxhost\"} OR vector(0)",
     "legendFormat": "Error RX"
    },
    {
     "expr": "vmware_host_net_errorTX_summation{host_name=~\"$esxhost\"} OR vector(0) ",
     "legendFormat": "Error TX"
    },
    {
     "expr": "vmware_host_net_droppedTX_summation{host_name=~\"$esxhost\"} OR vector(0)",
     "legendFormat": "Dropped TX"
    },
    {
     "expr": "vmware_host_net_droppedRX_summation{host_name=~\"$esxhost\"} OR vector(0)",
     "legendFormat": "Dropped RX"
    }
   ]
  },
  {
   "title": "Disk R/W Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "vmware_host_disk_read_average{host_name=~\"$esxhost\"}+vmware_host_disk_write_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Disk Read and Write"
    },
    {
     "expr": "vmware_host_disk_read_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Disk Read"
    },
    {
     "expr": "vmware_host_disk_write_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Disk Write"
    }
   ]
  }
 ]
}