{
 "title": "TechOps - Windows Server Metrics",
 "description": "General stats dashboard with node selector, uses metrics from prometheus-windows-exporter.install",
 "tags": [
  "windows",
  "windows_exporter",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(windows_system_system_up_time, job)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(windows_system_system_up_time{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Status",
   "type": "table",
   "description": "Current status of all Netalogue servers\n\n###### Notes\n\n+ `Blue`: constant value\n+ `Fds`: File Descriptors\n+ `Throttle`: flag `is_throttled`\n",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "windows_cs_hostname{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (windows_cs_logical_processors{job=\"$job\"})",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum by (instance) (rate(windows_cpu_time_total{mode!=\"idle\",job=\"$job\"}[5m])) * 100 / on (instance) windows_cs_logical_processors{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (windows_cs_physical_memory_bytes{job=\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (windows_os_physical_memory_free_bytes{job=\"$job\"} / windows_cs_physical_memory_bytes{job=\"$job\"}) * 100",
     "legendFormat": "Free Memory"
    },
    {
     "expr": "sum by (instance) (windows_logical_disk_free_bytes{volume=\"C:\",job=\"$job\"} / windows_logical_disk_size_bytes{volume=\"C:\",job=\"$job\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (windows_logical_disk_free_bytes{volume=\"D:\",job=\"$job\"} / windows_logical_disk_size_bytes{volume=\"D:\",job=\"$job\"}) * 100",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum by (instance) (windows_logical_disk_free_bytes{volume=\"E:\",job=\"$job\"} / windows_logical_disk_size_bytes{volume=\"E:\",job=\"$job\"}) * 100",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum by (instance) (windows_logical_disk_size_bytes{volume=\"C:\",job=\"$job\"}) ",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum by (instance) (windows_logical_disk_size_bytes{volume=\"D:\",job=\"$job\"}) ",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum by (instance) (windows_logical_disk_size_bytes{volume=\"E:\",job=\"$job\"}) ",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Server Stats (click on IP in server list above) - $server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "server"
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (mode) (rate(windows_cpu_time_total{instance=~\"$server\",mode!=\"idle\"}[5m])) * 100 / scalar(windows_cs_logical_processors{instance=~\"$server\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_sent_total{instance=~\"$server\"}[300s]) * 8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- rate(windows_net_bytes_received_total{instance=~\"$server\"}[300s]) <0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Logical disk write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_write_bytes_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[300s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- rate(windows_logical_disk_read_bytes_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[300s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_os_physical_memory_free_bytes{instance=\"$server\"} / windows_cs_physical_memory_bytes{instance=\"$server\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Memory",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Logical disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_split_ios_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[300s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "i/o {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk free space",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{instance=~\"$server\", volume !~\"HarddiskVolume.+\"} / windows_logical_disk_size_bytes{instance=~\"$server\", volume !~\"HarddiskVolume.+\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "free {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "system_threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_system_threads{instance=~\"$server\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "system_threads",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System exception dispatches",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_system_exception_dispatches_total{instance=~\"$server\"}[300s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "exceptions",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network discarded/error",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_packets_outbound_discarded_total{instance=~\"$server\", nic!~\"isatap.+\"}[300s]) + rate(windows_net_packets_outbound_errors_total{instance=~\"$server\"}[300s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_packets_received_discarded_total{instance=~\"$server\", nic!~\"isatap.+\"}[300s]) + rate(windows_net_packets_received_errors_total{instance=~\"$server\"}[300s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}