{
 "title": "TechOps - Postfix",
 "description": "Prometheus Postfix exporter metrics.",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(postfix_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "cleanup(8)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message processing rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_cleanup_messages_processed_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Rejection ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_cleanup_messages_rejected_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "qmgr(8)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Message insertion rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_qmgr_messages_inserted_size_bytes_count{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Message insertion bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_qmgr_messages_inserted_size_bytes_sum{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Message removal rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_qmgr_messages_removed_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "showq(8)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Number of enqueued messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "postfix_showq_message_size_bytes_count{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} {{ queue }}"
    }
   ]
  },
  {
   "title": "Size of enqueued messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "postfix_showq_message_size_bytes_sum{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} {{ queue }}"
    }
   ]
  },
  {
   "title": "Average age of enqueued messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(postfix_showq_message_age_seconds_count{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }} {{ queue }}"
    }
   ]
  },
  { "title": "smtp(8)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Message processing rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_smtp_delivery_delay_seconds_count{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }} {{stage}}"
    }
   ]
  },
  {
   "title": "Average delivery duration by stage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(postfix_smtp_delivery_delay_seconds_sum{instance=~\"$instance\"}[5m])) by (stage)) / (sum(rate(postfix_smtp_delivery_delay_seconds_count{instance=~\"$instance\"}[5m])) by (stage))",
     "legendFormat": "{{ stage }}"
    }
   ]
  },
  {
   "title": "TLS conection ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(postfix_smtp_tls_connections_total{instance=~\"$instance\"}[5m])) by (instance)) / (sum(rate(postfix_smtp_delivery_delay_seconds_count{instance=~\"$instance\"}[5m])) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TLS protocol/cipher usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_smtp_tls_connections_total[5m])",
     "legendFormat": "{{ protocol }}: {{ cipher }}, {{ trust }}"
    }
   ]
  },
  { "title": "smtpd(8)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Connect rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_smtpd_connects_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disconnect rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_smtpd_disconnects_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Connections lost",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_smtpd_connections_lost_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }} {{after_stage}}"
    }
   ]
  },
  {
   "title": "SASL authentication failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_smtpd_sasl_authentication_failures_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Forward-confirmed reverse DNS erros",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_smtpd_forward_confirmed_reverse_dns_errors_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Message processing rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_smtpd_messages_processed_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Rejection ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_smtpd_messages_rejected_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ instance }} {{code}}"
    }
   ]
  },
  {
   "title": "TLS conection ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(postfix_smtpd_tls_connections_total{instance=~\"$instance\"}[5m])) by (instance)) / (sum(rate(postfix_smtpd_connects_total{instance=~\"$instance\"}[5m])) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TLS protocol/cipher usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(postfix_smtpd_tls_connections_total[5m])",
     "legendFormat": "{{ protocol }}: {{ cipher }}, {{ trust }}"
    }
   ]
  }
 ]
}