{
 "title": "TechOps - Ebroker",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Ebroker instances",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_service_state{job=\"prod\", name=~\"guru.b2bi.ebroker.*\", state=\"running\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "On-Call",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_monitoring_pagerduty", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Out OIOSI Default Queued",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{job=\"rabbitmq\",queue=~\"oiosigw_default.app.queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Out OIOSI High Queued",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{job=\"rabbitmq\",queue=~\"oiosigw_high.app.queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "Change Events", "type": "annolist", "gridPos": { "h": 11, "w": 7, "x": 17, "y": 0 } },
  {
   "title": "ES Cluster Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{cluster=\"b2bi-02\",color=\"red\"}==1 or (elasticsearch_cluster_health_status{cluster=\"b2bi-02\",color=\"yellow\"}==1)+2 or\n(elasticsearch_cluster_health_status{cluster=\"b2bi-02\",color=\"green\"}==1)+4 "
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Processing Engine - ebroker records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Processing Engine - ebroker records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "ES Total Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{cluster=\"b2bi-02\"}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Outgoing GW - VLTrader records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Outgoing GW - VLTrader records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Incoming GW - VLTrader records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Incoming GW - VLTrader records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "ESXi Host In Maintenance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_host_maintenance_mode{cluster_name=~\"bifrost\"}==1) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"DE-X400\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"DE-X400\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Outgoing GW - X400 records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Outgoing GW - X400 records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Incoming GW - X400 records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Incoming GW - X400 records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "Default Outgoing OIOSI Delivered",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 11 },
   "targets": [
    {
     "expr": "sum_over_time(app_monitoring_tlog{name=~\"OIOD.*\"}[$__interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Transaction Log - Document Error Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum_over_time(app_monitoring_file_errors_total[15m])",
     "legendFormat": "{{errorCode}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Outgoing GW - OIOSI records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Outgoing GW - OIOSI records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Incoming GW - OIOSI records\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "app_monitoring_tlog{name=\"Transaction Log - Incoming GW - OIOSI records\"} offset 1w",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "High Outgoing OIOSI Delivered",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 15 },
   "targets": [
    {
     "expr": "sum_over_time(app_monitoring_tlog{name=~\"OIOH.*\"}[$__interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Transaction Log - Document status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(sum_over_time(app_monitoring_files_total[15m])) by (status) / on() group_left() sum(sum_over_time(app_monitoring_files_total[15m])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Out going OIOSI",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(app_monitoring_tlog{name=~\"OIOD.*\"}[$__range])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum_over_time(app_monitoring_tlog{name=~\"OIOH.*\"}[$__range])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "dotNet Error Queues",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (app_monitoring_dotNet_msgCount{queue=~\".*error.*|.*Error.*\"}) by (queue) > 0",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}