{
 "title": "TechOps - Alerts",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Production Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", env=\"production\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Test Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", env=\"test\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Demo Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", env=\"demo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 CPU Load",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk (5, 100 - (avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\",env=~\"production|test|demo\"}[2m])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Memory Used",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk (5, 100 - ((windows_os_physical_memory_free_bytes{env=~\"production|test|demo\"} / windows_cs_physical_memory_bytes) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Disk Used",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk (5, 100.0 - 100 * ((windows_logical_disk_free_bytes{volume!=\"HarddiskVolume1\",env=~\"production|test|demo\"} / 1024 / 1024 ) / (windows_logical_disk_size_bytes / 1024 / 1024)))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Production Alerts", "type": "alertlist", "gridPos": { "h": 18, "w": 24, "x": 0, "y": 10 } }
 ]
}