{
 "title": "TechOps - Log Events",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Windows - Failed Logons",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (count_over_time({job=\"windows\",channel=\"Security\"} | json | event_id = \"4625\" [$__range]))"
    }
   ]
  },
  {
   "title": "Windows - Account disabled, enabled, created or deleted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (count_over_time({job=\"windows\",channel=\"Security\"} |= \"4722\" |= \"4725\" |= \"4720\" |= \"4726\" [$__range]))"
    }
   ]
  },
  {
   "title": "Windows - Security Group Modifications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (count_over_time({job=\"windows\",channel=\"Security\"} |= \"4727\" |= \"4728\" |= \"4729\" |= \"4730\" |= \"4731\" |= \"4734\" |= \"4735\" |= \"4758\" [$__range]))"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{job=\"windows\",channel=\"Security\"} | json | event_id = \"4625\" "
    }
   ]
  }
 ]
}