groups:
  - name: prometheus.rules
    rules:
      - alert: InstanceDown
        expr: up{env="production"} == 0
        for: 15m
        labels:
          severity: "critical"
        annotations:
          group: "{{ $labels.group }}"
          host: "{{ $labels.instance }}"
          summary: "Endpoint {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."

      - alert: DeadMansSwitch
        expr: vector(1)
        labels:
          severity: "none"
        annotations:
          summary: "Alerting DeadMansSwitch"
          description: "This is a DeadMansSwitch meant to ensure that the entire Alerting
        pipeline is functional."
