groups:
  - name: prometheus.rules
    rules:
      - alert: HighNumberOfSnapshots
        expr: vmware_vm_snapshots > 3
        for: 30m
        labels:
          severity: warning
        annotations:
          host: "{{ $labels.host_name }}"
          summary: High Number of Snapshots (instance {{ $labels.instance }})
          description: "High snapshots number on {{ $labels.instance }}: {{ $value }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: VMWareDatastoreOutOfDiskSpace
        expr: 100 * vmware_datastore_freespace_size / vmware_datastore_capacity_size < 5
        for: 30m
        labels:
          severity: warning
        annotations:
          host: "{{ $labels.ds_name }}"
          summary: "{{ $value }}"
          description: "DS running out of space on {{ $labels.instance }}: {{ $value }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: VMWareESXiHostSensor
        expr: vmware_host_sensor_state != 2
        for: 30m
        labels:
          severity: warning
        annotations:
          host: "{{ $labels.host_name }}"
          summary: "{{ $labels.name }}"
          description: "Host status is not GREEN {{ $labels.instance }}: {{ $value }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"