{
 "title": "ONTAP: Cluster",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\",datacenter=\"$Datacenter\"},cluster)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   },
   {
    "name": "TopSVMs",
    "query": {
     "query": "query_result(topk($TopResources, avg_over_time(svm_vol_read_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}[${__range}])+avg_over_time(svm_vol_write_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}[${__range}])))"
    }
   },
   {
    "name": "TopSVMIOPs",
    "query": {
     "query": "query_result(topk($TopResources, avg_over_time(svm_vol_total_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}[${__range}])))"
    }
   },
   {
    "name": "TopSVMLatency",
    "query": {
     "query": "query_result(topk($TopResources, avg_over_time(svm_vol_avg_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}[${__range}])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes & Subsystems",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Cluster",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 1 },
   "repeat": "Cluster",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "node_new_status{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "cluster health status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_new_status{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "CPU busy",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_cpu_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Max Disk Utilization by Cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_disk_max_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Max Disk Utilization by Cluster",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_disk_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Capacity used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(aggr_space_used{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})/sum(aggr_space_total{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "$Cluster - subsystems",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cluster_subsystem_suppressed_alerts{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "cluster_subsystem_outstanding_alerts{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    },
    {
     "expr": "cluster_subsystem_new_status{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Power (Node)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(environment_sensor_power{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}) or vector(0))"
      }
     ]
    },
    {
     "title": "Max Node temp",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(environment_sensor_max_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})"
      }
     ]
    },
    {
     "title": "Max Node Fan Speed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(environment_sensor_max_fan_speed{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})"
      }
     ]
    },
    {
     "title": "Storage Nodes",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_labels{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "environment_sensor_power{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "environment_sensor_average_ambient_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "environment_sensor_min_ambient_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "environment_sensor_max_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "environment_sensor_average_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "environment_sensor_min_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "environment_sensor_max_fan_speed{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "environment_sensor_average_fan_speed{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "environment_sensor_min_fan_speed{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}"
      }
     ]
    },
    {
     "title": "Top Nodes by Power Consumed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "topk($TopResources,environment_sensor_power{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Top Nodes by Average Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "topk($TopResources,environment_sensor_average_temperature{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "max(volume_avg_latency{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}) by(cluster)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(volume_read_data{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}) by (cluster) + sum(volume_write_data{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}) by(cluster)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(volume_total_ops{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}) by (cluster)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Average Disk Utilization by Aggregate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(aggr_disk_busy{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}) by (cluster, aggr)",
       "legendFormat": "{{cluster}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Average Aggregate Space Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(aggr_space_used_percent{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}) by (cluster, aggr)",
       "legendFormat": "{{cluster}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Average CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(node_cpu_busy{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"}) by (cluster, node)",
       "legendFormat": "{{cluster}} - {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Efficiency Ratios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aggr_total_logical_used{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})/sum(aggr_total_physical_used{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})"
      }
     ]
    },
    {
     "title": "Total w/o Snapshots",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aggr_logical_used_wo_snapshots{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})/sum(aggr_physical_used_wo_snapshots{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})"
      }
     ]
    },
    {
     "title": "Total w/o Snapshots & FlexClones",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aggr_logical_used_wo_snapshots_flexclones{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})/sum(aggr_physical_used_wo_snapshots_flexclones{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})"
      }
     ]
    },
    {
     "title": "Total Logical Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (node) (aggr_total_logical_used{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Total Physical Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (node) (aggr_total_physical_used{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Logical Used w/o Snapshots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (node) (aggr_logical_used_wo_snapshots{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Physical Used w/o Snapshots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (node) (aggr_physical_used_wo_snapshots{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Logical Used w/o Snapshots & FlexClones",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (node) (aggr_logical_used_wo_snapshots_flexclones{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Physical Used w/o Snapshots & FlexClones",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (node) (aggr_physical_used_wo_snapshots_flexclones{datacenter=\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SVM Performance Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "svm_vol_avg_latency{cluster=~\"$Cluster\", svm=~\"$TopSVMLatency\"}",
       "legendFormat": "{{cluster}} - {{svm}}"
      }
     ]
    },
    {
     "title": "Top Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "svm_vol_read_data{cluster=~\"$Cluster\", svm=~\"$TopSVMs\"}+svm_vol_write_data{cluster=~\"$Cluster\",svm=~\"$TopSVMs\"}",
       "legendFormat": "{{cluster}} - {{svm}}"
      }
     ]
    },
    {
     "title": "Top IOPs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "svm_vol_total_ops{cluster=~\"$Cluster\", svm=~\"$TopSVMIOPs\"}",
       "legendFormat": "{{cluster}} - {{svm}}"
      }
     ]
    }
   ]
  }
 ]
}